# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g6arFUUwF0W8Ol_JTjYE5u1f4cWexL8Z
"""

import numpy as np
import statistics as st
import matplotlib.pyplot as plt

x = np.array([0, 1, 2, 3, 4, 5, 6])
y = np.array([4.2, 1.4, 0, -0.4, -0.1, 1.6, 4.1])

Desv_est = np.std(y)

Error_estandar = st.stdev(y) / np.sqrt(len(y))

Coef_correlacion = np.corrcoef(x, y)[0,1]

a, b, c = np.polyfit(x, y, 2)
poly = np.poly1d([a, b, c])


Coef_corr_ajust = np.corrcoef(x, poly(x))[0,1]

plt.scatter(x, y)
plt.plot(x, poly(x),'--', color='red',linewidth=1)
plt.title('Ajuste polinómico de segundo grado')
plt.show()

print("Desviación estándar de y:", Desv_est)
print("Error estándar de la media de y:", round(Error_estandar, 3))
print("Coeficiente de correlación:", Coef_correlacion)
print("Coeficiente de correlación del ajuste:", Coef_corr_ajust)